name: Check for broken links

on:
  push:
    branches:
      - master
      - main
    paths:
      - "_bibliography/**"
      - "_data/cv.yml"
      - "_data/socials.yml"
      - "_news/**"
      - "_pages/**"
      - "_teachings/**"
      - "assets/**"
      - ".github/workflows/broken-links.yml"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "_bibliography/**"
      - "_data/cv.yml"
      - "_data/socials.yml"
      - "_news/**"
      - "_pages/**"
      - "_teachings/**"
      - "assets/**"
      - ".github/workflows/broken-links.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          fail: true
          args: --user-agent 'curl/7.54' --max-retries 3 --retry-wait-time 2 --exclude-path _pages/404.md --verbose --no-progress './_bibliography/*.bib' './_data/cv.yml' './_data/socials.yml' './_news/**/*.md' './_pages/**/*.md' './_teachings/**/*.md'
